name: ci

on:
  push: { branches: [main] }
  pull_request:

jobs:
  linux-gcc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ runner.temp }}/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"
      - name: Configure
        run: cmake --preset linux-gcc -DGITVERSION_SEMVER=${{ steps.gitversion.outputs.semVer }}
      - name: Build
        run: cmake --build build/linux-gcc --parallel
      - name: Test
        run: ctest --test-dir build/linux-gcc --output-on-failure

  linux-clang:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0
      - name: Install Clang
        run: sudo apt-get update && sudo apt-get install -y clang
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ runner.temp }}/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"
      - name: Configure
        run: cmake --preset linux-clang -DGITVERSION_SEMVER=${{ steps.gitversion.outputs.semVer }}
      - name: Build
        run: cmake --build build/linux-clang --parallel
      - name: Test
        run: ctest --test-dir build/linux-clang --output-on-failure

  windows-msvc:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ runner.temp }}/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"
      - name: Configure
        run: cmake --preset windows-msvc -DGITVERSION_SEMVER=${{ steps.gitversion.outputs.semVer }}
      - name: Build
        run: cmake --build build/windows-msvc --parallel --config Release
      - name: Test
        run: ctest --test-dir build/windows-msvc --output-on-failure -C Release

  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        run: git submodule update --init --recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0
      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config ninja
      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ runner.temp }}/vcpkg"
          vcpkgJsonGlob: "vcpkg.json"
      - name: Configure
        run: cmake --preset macos -DGITVERSION_SEMVER=${{ steps.gitversion.outputs.semVer }}
      - name: Build
        run: cmake --build build/macos --parallel
      - name: Test
        run: ctest --test-dir build/macos --output-on-failure
